### ISSUE TITLE
No WiFi adapter available

### ISSUE THREAD

**Issue by StaubiKa** [mopplayer/lattepanda-mainline-4.11#5]
Hi mopplayer,

Unfortunately I still have issues to get WiFi up and running.
I followed your instructions and installed the latest z8300 patch but still can't connect to any WiFi. I don't see any adapter within the network settings. LAN itself is running fine but when I activate WiFi close the dialog and open it again it is disabled again.

Any ideas? Any log or screenshot I could provide? Already double-checked the BIOS settings in south bridge but they seem to be as supposed.
Same goes for BT - no connection possible.

Any help is (again) very welcome.

**Comment by mopplayer** [comment]
Hi, z8300 didn't need to change BIOS settings.
Is it Ubuntu, Debian 8 or Debian 9?
Please post dmesg, thanks.
Be ware of  current binary, it is for 4G/64G version.

**Comment by StaubiKa** [comment]
It is debian 9 with (currently) cinnamon. But also used GNOME and LXDE for testing.
Finally I want to use LXDE

Please find full dmesg attached (I set BIOS PCI to ACPI before boot again - no difference):
[dmesg.txt](https://github.com/mopplayer/lattepanda-mainline-4.11/files/1083079/dmesg.txt)

**Comment by StaubiKa** [comment]
By the way: I installed new BIOS some days ago
[https://github.com/LattePandaTeam/LattePanda-Win10-Software/tree/master/Bios/LattePanda v1.0/Auto Power on BIOS/4G](https://github.com/LattePandaTeam/LattePanda-Win10-Software/tree/master/Bios/LattePanda%20v1.0/Auto%20Power%20on%20BIOS/4G)

**Comment by mopplayer** [comment]
Oh, the DEB files couldn't be used for Debian9 by current state.
Because the existed UCM file, it will cause installation problem.
If you follow the steps, you have to add Intel ACPI firmware and Broadcom Wifi firmware.
It be provided by: [https://packages.ubuntu.com/xenial/linux-firmware](https://packages.ubuntu.com/xenial/linux-firmware)
Download and dpkg -i <pacakge>.
Please give me a feedback, thanks.

I will add some INFO for Debian9 recently.

**Comment by StaubiKa** [comment]
Ok, don't really get it... so I should reinstall plain debian 9 and no .deb package but the firmware provided in your link? This firmware includes both (ACPI and Broadcom)?
Sorry for the probably dump questions... 

Sure... you will get a prompt feedback :smile:

**Comment by mopplayer** [comment]
Yes, Ubuntu package is provided by default, but Debian is not.
Because it supports mainly for Ubuntu, I suggest to install this firmware package for Debian, follow the steps by steps.
If you could wait, I would release the Debian 9 DEB files.

But refer to your dmesg...
You should install the linux-firmware package, it would resolve your problem.

**Comment by StaubiKa** [comment]
Sure I can wait :-)
Honestly.. I really owe you something... let me know in case I can help you in any way (even though I have no idea how :-D)

**Comment by mopplayer** [comment]
mm, you could just install the the linux-firmware package.
[https://packages.ubuntu.com/xenial/linux-firmware](https://packages.ubuntu.com/xenial/linux-firmware)
It should be worked.

**Comment by StaubiKa** [comment]
Ok, just installed the linux-firmware package and BT / WiFi is working. MANY THANKS @mopplayer 
Not working is sound and (not really critical) the screen dimming for my attached touchpanel.

As I want to use the LP as a server I won't really need dimmable touchscreen and sound. But in case you would like to get a 100% solution I can easily help you to debug it. In that case just tell me what to do. But as mentioned: for me not critical.

(The touchpanel is the one from the kickstarter project.)

**Comment by StaubiKa** [comment]
HDMI sound works btw. It's the audio jack that does not work...

**Comment by mopplayer** [comment]
Hi, according to your dmesg, it should be work  (chtrt5645).
Please install pavucontrol to switch the DAI <-> output route.
The audio could not be outputted to jack and HDMI at the same time...

**Comment by StaubiKa** [comment]
Seems as if there is still some misconfiguration
![unbenannt](https://user-images.githubusercontent.com/22428396/27261376-265f965a-5442-11e7-9d77-cd611bafa53c.png)

I will try to check this later and give a feedback.
I tried the audio jack and hdmi audio seperately. So this shouldn't be the issue.

**Comment by mopplayer** [comment]
May Debian 9 (Testing) be still not stable on its package list.
Debian 8 have no problems about pulseaudio except breaking package dependence.

**Comment by StaubiKa** [comment]
Either this or maybe because I used cinnamon as desktop environment. I'll give it a try with lxde and a clean new Debian 9 installation later.
As this GitHub issue was regarding WiFi and BT which is now resolved I'll close this thread.
Thanks!!
